version: '3.5'

services:
  app1: &api
    build: .
    environment:
      SERVER_PORT: 8080
      DB_HOST: localhost
      POOL_SIZE: 30
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.6GB'
    network_mode: "host"

  app2:
    <<: *api
    environment:
      SERVER_PORT: 8081
      DB_HOST: localhost
      POOL_SIZE: 30
    depends_on:
      - db
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  db: # Banco de dados
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_db
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha_db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.4GB'